### ISSUE TITLE
Add a sample to demonstrate SolCache usage

### ISSUE THREAD

**Issue by MichaelHussey** [SolaceSamples/solace-samples-java#19]
It's pretty easy to enhance the TopicSubscriber sample so that it can retrieve the first message from a SolCache cluster:

``` 
// Add Cache handling
// Requests the most recent message on the topic, using default timeout 10sec
CacheSessionProperties props = new CacheSessionProperties(cacheName);
CacheSession cacheSession;
try {
 cacheSession = session.createCacheSession(props);
						
  cacheSession.sendCacheRequest(1L, topic, false, CacheLiveDataAction.FULFILL);
			
} catch (JCSMPException e) {
  // TODO Auto-generated catch block
  e.printStackTrace();
}
```
There doesn't seem to be any sample online available which shows this.

**Comment by mdspielman** [comment]
This is a good suggestion. Covering cache requests is something that we will look to cover as we merge the advanced samples that are currently included in the Solace Java API that you can download from http://dev.solace.com/downloads/

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. :sleeping:
To have this issue re-opened please add a comment below with a detailed explanation.  
Thank you for your contributions :heart:
