### ISSUE TITLE
Add TLS sample with explanation of API parameters

### ISSUE THREAD

**Issue by mdspielman** [SolaceSamples/solace-samples-java#2]
It would be nice to illustrate how to connect securely to Solace Message Routers. I believe the solution to this would be in two parts.
1. Create a new sample that shows and explains the following
   - How to establish a secure session with basic authentication
   - Explain the various ways of passing the TLS properties to the API (ENV, session properties, etc.)
   - How to validate enable certificate validation in the client application
   - How to authenticate the application using a client certificate. 
2. In general in the other getting started tutorials, add a small note explaining how use environment variable at runtime to secure the connection if users want and point at this new tutorial for more details.

Some of the details that need to be explained are covered in Solace documentation here:
- https://sftp.solacesystems.com/Portal_Docs/#page/Solace_Messaging_APIs_Developer_Guide/Creating_Client_Sessions.html#ww664250

Let's do this first in the Java API, once done we can look at porting this sample to the other Solace APIs.

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. :sleeping:
To have this issue re-opened please add a comment below with a detailed explanation.  
Thank you for your contributions :heart:
