### ISSUE TITLE
README.md showing markup

### ISSUE THREAD

**Issue by jondiamond** [SolaceSamples/solace-samples-java#34]
The README.md is not properly rendered and contains markup:

The "Getting Started" tutorials will get you up to speed and sending messages with Solace technology as quickly as possible. There are three ways you can get started:

Follow [these instructions]({{ site.links-solaceCloud-setup }}){:target="_top"} to quickly spin up a cloud-based Solace messaging service for your applications.
Follow [these instructions]({{ site.docs-vmr-setup }}){:target="_top"} to start the Solace VMR in leading Clouds, Container Platforms or Hypervisors. The tutorials outline where to download and how to install the Solace VMR.
If your company has Solace message routers deployed, contact your middleware team to obtain the host name or IP address of a Solace message router to test against, a username and password to access it, and a VPN in which you can produce and consume messages.

This applies to most other samples README.md too.

**Comment by mdspielman** [comment]
This issue has been selected for resolution by Solace.

**Comment by mdspielman** [comment]
Fixed in latest pull request.
