### ISSUE TITLE
Persistence with Queues: Creating topic not queue

### ISSUE THREAD

**Issue by brijendrak** [SolaceSamples/solace-samples-java#46]
Hi Team,

I think we have issue with documentation in Persistence with Queues
In section Sending a message to a queue
we are creating topic as below whereas we should be creating Queue
final Topic topic = JCSMPFactory.onlyInstance().createTopic("tutorial/topic");

**Comment by mdspielman** [comment]
Thank you for pointing that out. It is indeed an error which should be fixed.
