### ISSUE TITLE
TopicSubscriber connection was forcibly closed

### ISSUE THREAD

**Issue by liangzhijian0** [SolaceSamples/solace-samples-java#53]
When TopicPublisher publish a message,TopicSubscriber connection was forcibly closed.And the error is "An existing connection was forcibly closed by the remote host".

**Comment by mdspielman** [comment]
This is sometimes seen if the two applications are using the same client name for their connection. Did you adjust the samples at all to set a client name? Or if not, can you add some further information about what you have looked at to debug this issue in terms of application logs of PubSub+ Broker event logs.

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. :sleeping:
To have this issue re-opened please add a comment below with a detailed explanation.  
Thank you for your contributions :heart:
