### ISSUE TITLE
Search-replace for "solace-samples-template"

### ISSUE THREAD

**Issue by aaron-613** [SolaceSamples/solace-samples-java#56]
Looks like someone forgot to replace the default "solace-samples-template" with "solace-samples-java" in the CONTRIBUTING.md file.  Made for some confusion as a first-time GitHub contributor.

Also noticed this in some other SolaceSamples projects (e.g. Node.js, C, etc.), but not all (e.g. the JavaScript one is ok).

**Comment by Mrc0113** [comment]
Closing stale issue due to inactivity. :sleeping:
To have this issue re-opened please add a comment below with a detailed explanation.  
Thank you for your contributions :heart:
